spring.application.name=MAL2021_Assessment2

# Use H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Create the tables automatically based on your Models
spring.jpa.hibernate.ddl-auto=update

# Optional: Enable the H2 Console so you can see your data in a browser at /h2-console
spring.h2.console.enabled=true
